#definimos el tipo de base de datos que vamos a usar, en este caso postgresql
quarkus.datasource.db-kind=postgresql

#Usuario y contraseña para acceder a la base de datos
quarkus.datasource.username=postgres
quarkus.datasource.password=labcom,2015

#URL de conexión a la base de datos, en este caso localhost con el puerto 5432 y el nombre de la base de datos pa2db
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2db

#Parametros recomendables
#Sincroniza lo que tengo en el código con la base de datos, es decir, si creo una nueva entidad o modifico una existente, se reflejará en la base de datos, cada que se actualiza
quarkus.hibernate-orm.database.generation=update

# Cada vez que se inicie la aplicación, se eliminará la base de datos y se creará de nuevo, esto es útil para pruebas y desarrollo, pero no se recomienda para producción
#quarkus.hibernate-orm.database.generation=drop-and-create

# Cada vez que se ejecute una consulta SQL, se mostrará en la consola, esto es útil para depurar y entender qué consultas se están ejecutando
quarkus.hibernate-orm.log.sql=true

# Especifica un script SQL que se ejecutará al iniciar la aplicación, en este caso import.sql, que se encuentra en el classpath, este script puede contener instrucciones para insertar datos de prueba o inicializar la base de datos
# quarkus.hibernate-orm.sql-load-script=import.sql

#quarkus.transaction-manager.default-transaction-timeout=PT30M
quarkus.transaction-manager.default-transaction-timeout=PT240S